rewrite countrycode and turn off checks to make the redirection work
jonasbn/perl-date-holidays pull request #53
Opened 2021-09-17 13:22 UTC by qorron

# Description

I ran across this issue today and it took me a while to make it work with US as country code.

How to reproduce:
`perl -E 'use Date::Holidays; $dh = Date::Holidays->new(countrycode=>"US");'`

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project, please see the [contribution guidelines](https://github.com/jonasbn/perl-date-holidays/blob/master/CONTRIBUTING.md).
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas (-> simple change)
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes (they did not complete in the first place because a lot of Date::Holidays::XX modules are not in this repo)
- [ ] Any dependent changes have been merged and published in downstream modules (none required)

You might think, that this is one crazy checklist, but it is just as much written for the maintainer of the involved software :-)

2022-02-17 08:25 UTC, jonasbn requested changes
The proposed change looks promising. But please leave out the change to the `Makefile.PL`

2022-02-28 10:20 UTC, qorron commented
the commit adb1294 was not intended to be in the PR. Not sure how it got there, I try to clean it up.

2022-02-28 10:39 UTC, qorron commented
ok, the PR tracks the master branch and dows not stay put on the commit it was created upon. makes sense actually.
I kept the compatibility change on a different branch.

2022-02-28 19:54 UTC, jonasbn approved these changes
Looks good, thanks for the contribution

2022-02-28 19:54 UTC, merged